name: Deploy to Azure App Service

on:
  push:
    branches: [ chat-with-sql ]
  workflow_dispatch:  # Allows manual triggering

env:
  NODE_VERSION: '17.x'
  PYTHON_VERSION: '3.11'
  AZURE_WEBAPP_NAME: 'clvr-gpt4-chatbot'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }}" >> .env
        echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "AZURE_OPENAI_MODEL=${{ vars.AZURE_OPENAI_MODEL }}" >> .env
        echo "AZURE_OPENAI_PREVIEW_API_VERSION=${{ vars.AZURE_OPENAI_PREVIEW_API_VERSION }}" >> .env
        echo "DB_TOP_K=${{ vars.DB_TOP_K }} >> .env"
        echo "MAX_TOKENS=${{ vars.MAX_TOKENS }} >> .env"
        echo "STREAM=${{ vars.STREAM }} >> .env"
        echo "SYSTEM_MESSAGE=${{ vars.SYSTEM_MESSAGE }} >> .env"
        echo "TEMPERATURE=${{ vars.TEMPERATURE }} >> .env"
        echo "TOP_P=${{ vars.TOP_P }} >> .env"

  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Building web app
      uses: azure/appservice-build@v2

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
